name: Upload to Codecov

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Pytohn
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage codecov pytest pytest-cov pytest-mock pytest-console-scripts
        pip install .
    - name: Generate coverage file
      env:
        PACK_NAME: 'hellopypi_bfc'
      run: |
        # these two lines work for hellopypi, but not scimma:
        coverage run -m pytest || true
        coverage xml
        #pytest --cov-report term --cov-report xml # this line sometimes works for hellopypi, but gives 0% coverage for scimma
        #python -m pytest --cov-report term --cov-report xml:coverage.xml --cov $PACK_NAME # this line works for scimma, but not hellopypi
    - name: Upload results to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        file: coverage.xml # optional
        flags: pytest # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)

        
