name: Upload to Codecov

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Pytohn
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage codecov
    - name: Generate coverage file
      run: |
        coverage run -m pytest
        coverage xml
    - name: Upload results to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        file: coverage.xml # optional
        flags: pytest # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
