name: Create a release from a tag

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create release through REST API
      env:
        ORG_NAME: 'bfc5288'
        REPO_NAME: 'hellopypi'
        RELEASE_USER: ${{ secrets.RELEASE_USER }}
        RELEASE_PW: ${{ secrets.RELEASE_PW }}
      run: |
        CHANGELOG_URL='https://raw.githubusercontent.com/${ORG_NAME}/${REPO_NAME}/master/CHANGELOG.md'
        generate_release_data() {
        cat <<EOF
        {
        "tag_name":"$GITHUB_REF",
        "name":"Test release",
        "body":"description of release",
        "draft": false,
        "prerelease": true
        }
        EOF
        }

        curl \
            -X POST \
            -u $RELEASE_USER:$RELEASE_PW \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${ORG_NAME}/{$REPO_NAME}/releases \
            -d "$(generate_release_data)"
