name: Create a release from a tag

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create release through REST API
      env:
        RELEASE_USER: ${{ secrets.RELEASE_USER }}
        RELEASE_PW: ${{ secrets.RELEASE_PW }}
        RELEASE_URL: 'https://api.github.com/repos/bfc5288/hellopypi/releases'
      run: |
        curl \
            -X POST \
            -u $RELEASE_USER:$RELEASE_PW \
            -H "Accept: application/vnd.github.v3+json" \
            $RELEASE_URL \
            -d '{
                 "tag_name":"v3.2.0a2",
                 "name":"test release",
                 "body":"description of release",
                 "draft": true,
                 "prerelease": true
                 }'
